# Generated by Django 6.0.5 on 2026-06-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('movie_type', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('SCI-FI', 'Sci-Fi'), ('HORROR', 'Horror')], default='ACTION', max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
